### ISSUE TITLE
Need a styling hook for each section

### ISSUE THREAD

**Issue by camwiegert** [adorableio/woo#33]
It'd be nice to have a styling hook per-section. I often want to style something just a little differently for display on the style guide.

Right now, in [that view](https://github.com/adorableio/woo/blob/master/app/views/woo/shared/_single_page.html.haml), there's an ID being applied to the anchor on [line 3](https://github.com/adorableio/woo/blob/master/app/views/woo/shared/_single_page.html.haml#L3). I'm wondering if we could move that up to the parent `<dl>` so it'd be easy to target the whole section.

**Comment by itsthatguy** [comment]
Can we facilitate a solution to the problem? yes
Can we move the identifier to the dl? no

The reason we can't move it to the DL as is, is because  we use the `single_page` for the [ui_elements](https://github.com/adorableio/woo/blob/master/app/views/woo/styleguide/index.html.haml#L3) as well. We need a few more changes to make this happen. Do you have any thoughts on how to achieve it?

**Comment by camwiegert** [comment]
Yeah, my original intention was to move it for the ui_elements, not for pages. When I said "per-section" above I meant each section (`<dl>`) on the [index](https://github.com/adorableio/woo/blob/master/app/views/woo/styleguide/index.html.haml#L3). I see now that it's being used to render separate pages too.

I'd offer a solution, but I'm a little unclear on why moving the ID is a problem.

**Comment by itsthatguy** [comment]
I'll take another look. I might have misread something.
